"""High-level Eradiate simulator interface."""

from pathlib import Path
from typing import Optional

# Import with optional dependencies
try:
    import eradiate
    ERADIATE_AVAILABLE = True
except ImportError:
    ERADIATE_AVAILABLE = False

from ...config import RenderConfig
from .experiment import create_experiment
from .renderer import render_experiment


class EradiateSimulator:
    """High-level interface for Eradiate radiative transfer simulations.
    
    This class provides a clean API for running Eradiate simulations with
    scenes generated by s2gos-generator.
    """
    
    def __init__(self, render_config: RenderConfig):
        """Initialize the Eradiate simulator.
        
        Args:
            render_config: Rendering configuration (sensors, illumination)
            
        Raises:
            ImportError: If Eradiate is not available
        """
        if not ERADIATE_AVAILABLE:
            raise ImportError("Eradiate is not available. Install with: pip install eradiate[kernel]")
        
        self.render_config = render_config
        
    def create_experiment(self, scene_config, scene_dir: Path):
        """Create an Eradiate experiment from scene configuration.
        
        Args:
            scene_config: Scene configuration from s2gos_generator
            scene_dir: Directory containing scene assets
            
        Returns:
            Eradiate AtmosphereExperiment ready for rendering
        """
        return create_experiment(scene_config, self.render_config, scene_dir)
        
    def run_simulation(self, scene_config, scene_dir: Path, output_dir: Optional[Path] = None):
        """Complete simulation: create experiment + render + save results.
        
        Args:
            scene_config: Scene configuration from s2gos_generator
            scene_dir: Directory containing scene assets (meshes, textures)
            output_dir: Output directory for results (defaults to scene_dir/eradiate_renders)
            
        Returns:
            dict: Simulation results containing:
                - success: bool indicating if simulation succeeded
                - raw_results: Path to NetCDF results file (if successful)
                - rgb_image: Path to RGB visualization (if successful)
                - output_dir: Path to output directory
                - error: Error message (if failed)
        """
        return render_experiment(scene_config, self.render_config, scene_dir, output_dir)
        
    def render_experiment_object(self, experiment, output_dir: Path):
        """Render a pre-created Eradiate experiment.
        
        Args:
            experiment: Eradiate AtmosphereExperiment object
            output_dir: Directory for render outputs
            
        Returns:
            dict: Rendering results
        """
        if not ERADIATE_AVAILABLE:
            raise ImportError("Eradiate is not available")
            
        print("Running Eradiate simulation...")
        eradiate.run(experiment)
        
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Save results
        raw_output = output_dir / "eradiate_results.nc"
        results_ds = experiment.results["perspective_view"] 
        results_ds.to_netcdf(raw_output)
        
        print(f"Simulation complete: {raw_output}")
        
        return {
            "success": True,
            "raw_results": raw_output,
            "output_dir": output_dir,
            "experiment": experiment
        }